[package]
name = "cedar-rust-hello-world"
edition = "2018"

version = "2.0.0"
publish = false

[dependencies]
serde_json = "1.0"

[dependencies.cedar-policy]
version = "2.3.0"
git = "https://github.com/prakol16/cedar.git"
branch = "more_generalized_entity_store_merge"
